package com.woleapp.netpos.qrgenerator.utils

const val PREF_USER = "user"
const val AMOUNT_AND_TALLY_NUMBER = "AMOUNT_AND_TALLY_NUMBER"
const val REQUEST_CODE =1
const val STRING_TAG_JAVASCRIPT_INTERFACE_TAG = "Android"
const val PIN_BLOCK_RK = "PIN_BLOCK_RK"
const val PIN_BLOCK_BK = "PIN_BLOCK_BK"
const val QR_PIN_PAD = "QR_PIN_PAD"
const val QR_TRANSACTION_RESULT_REQUEST_KEY = "QR_TRANSACTION_RESULT_REQUEST_KEY"
const val TALLY_WALLET_QR_TRANSACTION_RESULT_REQUEST_KEY = "TALLY_WALLET_QR_TRANSACTION_RESULT_REQUEST_KEY"
const val QR_TRANSACTION_RESULT_BUNDLE_KEY = "QR_TRANSACTION_RESULT_BUNDLE_KEY"
const val TALLY_WALLET_QR_TRANSACTION_RESULT_BUNDLE_KEY = "TALLY_WALLET_QR_TRANSACTION_RESULT_BUNDLE_KEY"
const val STRING_QR_RESPONSE_MODAL_DIALOG_TAG = "STRING_QR_RESPONSE_MODAL_DIALOG_TAG"
const val PREF_GENERATE_QR = "PREF_GENERATE_QR"
const val QR_FILE_DOWNLOAD = "QR"
const val PIN_PASSWORD = "pin_password"
const val REQUEST_CAMERA_CODE_PERMISSION = 1
const val PREF_TALLY_WALLET = "PREF_TALLY_WALLET"
const val USER_TOKEN = "USER_TOKEN"
const val TRANS_ID_AND_AMOUNT = "TRANS_ID_AND_AMOUNT"
const val STRING_PIN_BLOCK_DIALOG_TAG = "STRING_PIN_BLOCK_DIALOG_TAG"
const val RESEND_PAYLOAD_FOR_VERVE = "RESEND_PAYLOAD_FOR_VERVE"
const val CHARGE_AMOUNT = 1.00



