package com.woleapp.netpos.qrgenerator.utils

const val PREF_QR_PASSWORD = "qr_password"
const val PREF_USER = "user"
const val PREF_QR = "qr"
const val REQUEST_CODE =1
const val WEB_VIEW_JAVASCRIPT_TAG = "WEB"
const val PIN_BLOCK_RK = "PIN_BLOCK_RK"
const val PIN_BLOCK_BK = "PIN_BLOCK_BK"
const val QR_PIN_PAD = "QR_PIN_PAD"
const val QR_TRANSACTION_RESULT_REQUEST_KEY = "QR_TRANSACTION_RESULT_REQUEST_KEY"
const val QR_TRANSACTION_RESULT_BUNDLE_KEY = "QR_TRANSACTION_RESULT_BUNDLE_KEY"
const val STRING_QR_RESPONSE_MODAL_DIALOG_TAG = "STRING_QR_RESPONSE_MODAL_DIALOG_TAG"
